# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DiodeCalibration_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxUmschalter = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxUmschalter.setObjectName("checkBoxUmschalter")
        self.horizontalLayout.addWidget(self.checkBoxUmschalter)
        self.spinBoxPower = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxPower.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxPower.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxPower.setSingleStep(1.0)
        self.spinBoxPower.setProperty("value", 10.0)
        self.spinBoxPower.setObjectName("spinBoxPower")
        self.horizontalLayout.addWidget(self.spinBoxPower)
        self.spinBoxFrom = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxFrom.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxFrom.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxFrom.setObjectName("spinBoxFrom")
        self.horizontalLayout.addWidget(self.spinBoxFrom)
        self.spinBoxTo = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxTo.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxTo.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxTo.setProperty("value", 40.0)
        self.spinBoxTo.setObjectName("spinBoxTo")
        self.horizontalLayout.addWidget(self.spinBoxTo)
        self.spinBoxStep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spinBoxStep.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBoxStep.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBoxStep.setDecimals(4)
        self.spinBoxStep.setProperty("value", 0.001)
        self.spinBoxStep.setObjectName("spinBoxStep")
        self.horizontalLayout.addWidget(self.spinBoxStep)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.graphicsView = Plot_pyqtgraph(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonLoad)
        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_2.addWidget(self.pushButtonStart)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxUmschalter.setText(_translate("MainWindow", "Use Zirkulators/Umschalter?"))
        self.spinBoxPower.setPrefix(_translate("MainWindow", "Microwave Power: "))
        self.spinBoxPower.setSuffix(_translate("MainWindow", " dBm"))
        self.spinBoxFrom.setPrefix(_translate("MainWindow", "From: "))
        self.spinBoxFrom.setSuffix(_translate("MainWindow", " GHz"))
        self.spinBoxTo.setPrefix(_translate("MainWindow", "To: "))
        self.spinBoxTo.setSuffix(_translate("MainWindow", " GHz"))
        self.spinBoxStep.setPrefix(_translate("MainWindow", "In steps of: "))
        self.spinBoxStep.setSuffix(_translate("MainWindow", " GHz"))
        self.pushButtonLoad.setText(_translate("MainWindow", "Load Frequenzliste"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
from customwidgets import Plot_pyqtgraph
